import Head from 'next/head';
import React from 'react';
import styles from 'styles/Home.module.css';
import Logo from 'components/Logo';
import Sidebar from 'components/Sidebar';

interface HomeProps {
  children: React.ReactNode;
  page?: string;
  hasHeader?: boolean;
  hasFooter?: boolean;
  hasMenu?: boolean;
}

//todo: fix layout design bugs

const MainLayout: React.FC<HomeProps> = ({
  children,
  page = 'Home',
  hasHeader = false,
  hasFooter = false,
  hasMenu = false,
}) => {
  return (
    <>
      <Head>
        <title>{`Gift-time - ${page}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className={`${hasMenu && 'grid'} ${styles.container} bg-white-off`}
        >
          {hasMenu && (
            <aside className={styles.sidebar}>
              <Sidebar />
            </aside>
          )}
          <section className={styles.children}>
            {hasHeader && (
              <header className="flex mb-5 justify-center items-center py-3 flex-col border-b">
                <h2 className="font-medium text-4xl">{page}</h2>
              </header>
            )}
            {children}
          </section>
        </div>
      </main>
      {/* {hasFooter && (
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      )} */}
    </>
  );
};

export default MainLayout;
