import Sidebar from 'components/Sidebar';
import Head from 'next/head';
import React from 'react';
import styles from 'styles/Home.module.css';

interface HomeProps {
  children: React.ReactNode;
  page?: string;
  hasHeader?: boolean;
  hasMenu?: boolean;
}

//TODO: fix layout design bugs

const MainLayout: React.FC<HomeProps> = ({
  children,
  page = 'Home',
  hasHeader = false,
  hasMenu = false,
}) => {
  return (
    <>
      <Head>
        <title>{`${page}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className={`${hasMenu && 'grid'} ${styles.container} bg-white-off`}>
          {hasMenu && (
            <aside className={styles.sidebar}>
              <Sidebar />
            </aside>
          )}
          <section className={styles.children}>
            {hasHeader && (
              <header className="flex mb-5 justify-center items-center py-3 flex-col border-b">
                <h2 className="font-medium text-4xl">{page}</h2>
              </header>
            )}
            {children}
          </section>
        </div>
      </main>
    </>
  );
};

export default MainLayout;
